"""Added columns to Vector table

Revision ID: 4c75e0271cec
Revises: 1abd517b82eb
Create Date: 2022-01-18 09:24:48.434063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c75e0271cec"
down_revision = "1abd517b82eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("qualifiers", schema=None) as batch_op:
        batch_op.alter_column("feature", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("vectors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bacterial_strain", sa.String()))
        batch_op.add_column(sa.Column("responsible", sa.String()))
        batch_op.add_column(sa.Column("group", sa.String()))
        batch_op.add_column(sa.Column("bsa1_overhang", sa.String()))
        batch_op.add_column(sa.Column("selection", sa.String()))
        batch_op.add_column(sa.Column("cloning_technique", sa.String()))
        batch_op.add_column(sa.Column("is_BsmB1_free", sa.String()))
        batch_op.add_column(sa.Column("notes", sa.String()))
        batch_op.add_column(sa.Column("REase_digest", sa.String()))

        batch_op.alter_column(
            "bacterial_strain", existing_type=sa.String(), nullable=False
        )
        batch_op.alter_column("responsible", existing_type=sa.String(), nullable=False)
        batch_op.alter_column("group", existing_type=sa.String(), nullable=False)
        batch_op.alter_column(
            "bsa1_overhang", existing_type=sa.String(), nullable=False
        )
        batch_op.alter_column("selection", existing_type=sa.String(), nullable=False)
        batch_op.alter_column(
            "cloning_technique", existing_type=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "is_BsmB1_free", existing_type=sa.String(), nullable=False
        )
        batch_op.alter_column("notes", existing_type=sa.String(), nullable=False)
        batch_op.alter_column("REase_digest", existing_type=sa.String(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vectors", schema=None) as batch_op:
        batch_op.drop_column("REase_digest")
        batch_op.drop_column("notes")
        batch_op.drop_column("is_BsmB1_free")
        batch_op.drop_column("cloning_technique")
        batch_op.drop_column("selection")
        batch_op.drop_column("bsa1_overhang")
        batch_op.drop_column("group")
        batch_op.drop_column("responsible")
        batch_op.drop_column("bacterial_strain")

    with op.batch_alter_table("qualifiers", schema=None) as batch_op:
        batch_op.alter_column("feature", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
