"""Added columns to Vector table

Revision ID: 6b5131dfa3d4
Revises: 1abd517b82eb
Create Date: 2022-01-14 17:46:54.420227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b5131dfa3d4"
down_revision = "1abd517b82eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("qualifiers", "feature", existing_type=sa.INTEGER(), nullable=False)
    op.add_column("vectors", sa.Column("bacterial_strain", sa.String(), nullable=False))
    op.add_column("vectors", sa.Column("responsible", sa.String(), nullable=False))
    op.add_column("vectors", sa.Column("group", sa.String(), nullable=False))
    op.add_column("vectors", sa.Column("bsa1_overhang", sa.String(), nullable=False))
    op.add_column("vectors", sa.Column("selection", sa.String(), nullable=False))
    op.add_column(
        "vectors", sa.Column("cloning_technique", sa.String(), nullable=False)
    )
    op.add_column("vectors", sa.Column("is_BsmB1_free", sa.String(), nullable=False))
    op.add_column("vectors", sa.Column("notes", sa.String(), nullable=True))
    op.add_column("vectors", sa.Column("REase_digest", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vectors", "REase_digest")
    op.drop_column("vectors", "notes")
    op.drop_column("vectors", "is_BsmB1_free")
    op.drop_column("vectors", "cloning_technique")
    op.drop_column("vectors", "selection")
    op.drop_column("vectors", "bsa1_overhang")
    op.drop_column("vectors", "group")
    op.drop_column("vectors", "responsible")
    op.drop_column("vectors", "bacterial_strain")
    op.alter_column("qualifiers", "feature", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
